# test-demo:
#   stage: test
#   script:
#     - cd demo
#     - bundle install
#     - rails db:migrate RAILS_ENV=test
#     - PARALLEL_WORKERS=1 rails test
#   only:
#     - demo

deploy-demo:
  stage: deploy
  # before_script:
  #   - apt-get update -qq
  #   - apt-get install -y libmysqlclient-dev
  #   - apt-get install cron
  script:
    - rsync -arv --delete --exclude="*.sqlite3" ./demo /
    - cd /demo
    - bundle install
    - rails db:migrate
    - npm config set registry https://registry.npmmirror.com
    - yarn config set registry https://registry.npmmirror.com
    - rm -f yarn.lock
    - yarn cache clean
    - yarn install
    - yarn build
    # - whenever --update-crontab
    - sv restart demo
  only:
    - demo