test-project:
  stage: test
  script:
    - cd project
    - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    - apt install -y nodejs
    - bundle install
    - npm cache clean --force
    - npm install
    - npm run build
    - rails db:migrate RAILS_ENV=test
    - PARALLEL_WORKERS=1 rails test
  only:
    - project

deploy-project:
  stage: deploy
  script:
    - rsync -arv --delete --exclude="*.sqlite3" --exclude="node_modules" ./project /
    - cd /project
    - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    - apt install -y nodejs
    - bundle install
    - npm cache clean --force
    - npm install
    - npm run build
    - rails db:migrate
    - sv restart project
  only:
    - project