test-project:
  stage: test
  script:
    - cd project
    # - apt install -y libvips42 libvips-dev
    # - apt remove -y nodejs npm libnode-dev
    # - apt autoremove -y
    # - apt clean
    # - apt install -y nodejs
    - bundle install
    # - npm config set registry https://registry.npmmirror.com
    # - yarn config set registry https://registry.npmmirror.com
    # - rm -f yarn.lock
    # - yarn cache clean
    - yarn install
    - yarn build
    - rails db:migrate RAILS_ENV=test
    - PARALLEL_WORKERS=1 rails test
  only:
    - project

deploy-project:
  stage: deploy
  script:
    - rsync -arv --delete --exclude="node_modules" ./project /
    - cd /project
    - bundle install
    - yarn install
    - yarn build
    - rails db:migrate
    - sv restart project
  only:
    - project