test-project:
  stage: test
  script:
    - cd project
    - gem install nokogiri
    - bundle install
    - npm install
    - npm run build
    - rails db:migrate RAILS_ENV=test
    - PARALLEL_WORKERS=1 rails test
  only:
    - project

deploy-project:
  stage: deploy
  script:
    - rsync -arv --delete --exclude="*.sqlite3" --exclude="node_modules" ./project /
    - cd /project
    - gem install nokogiri
    - bundle install
    - npm install
    - npm run build
    - rails db:migrate
    - sv restart project
  only:
    - project